export const WORDS = [
  {
    no: "som",
    en: "as / which / who",
    pos: "conj",
    examples: [
      { no: "Mannen som står der.", en: "The man who stands there." },
      { no: "Boken som jeg leste, var god.", en: "The book that I read was good." }
    ]
  },
  {
    no: "jeg",
    en: "I",
    pos: "pron",
    examples: [
      { no: "Jeg er trøtt.", en: "I am tired." },
      { no: "Jeg lærer norsk.", en: "I am learning Norwegian." }
    ]
  },
  { no: "hans", en: "his", pos: "pron", example: "Det er hans bok.", example_en: "That is his book." },
  { no: "at", en: "that", pos: "conj", example: "Jeg vet at du kommer.", example_en: "I know that you are coming." },
  { no: "han", en: "he", pos: "pron", example: "Han er lærer.", example_en: "He is a teacher." },
  { no: "var", en: "was / were", pos: "verb", example: "Det var gøy.", example_en: "It was fun." },
  { no: "for", en: "for / because", pos: "prep", example: "Dette er for deg.", example_en: "This is for you." },
  { no: "på", en: "on / at", pos: "prep", example: "Boken ligger på bordet.", example_en: "The book is on the table." },
  { no: "er", en: "is / are / am", pos: "verb", example: "Hun er hjemme.", example_en: "She is at home." },
  { no: "med", en: "with", pos: "prep", example: "Jeg går med deg.", example_en: "I go with you." },
  { no: "de", en: "they", pos: "pron", example: "De kommer snart.", example_en: "They are coming soon." },
  { no: "være", en: "to be", pos: "verb", example: "Å være glad er viktig.", example_en: "To be happy is important." },
  { no: "ett", en: "one", pos: "num", example: "Jeg har ett spørsmål.", example_en: "I have one question." },
  { no: "har", en: "have / has", pos: "verb", example: "Jeg har en bil.", example_en: "I have a car." },

  {
    no: "dette",
    en: "this",
    pos: "pron",
    examples: [
      { no: "Dette er bra.", en: "This is good." },
      { no: "Dette huset er gammelt.", en: "This house is old." }
    ]
  },

  { no: "fra", en: "from", pos: "prep", example: "Jeg er fra Norge.", example_en: "I am from Norway." },
  { no: "etter", en: "after", pos: "prep", example: "Etter jobb drar jeg hjem.", example_en: "After work I go home." },
  { no: "varm", en: "warm", pos: "adj", example: "Maten er varm.", example_en: "The food is warm." },
  { no: "ordet", en: "the word", pos: "noun", example: "Jeg forstår ordet.", example_en: "I understand the word." },

  {
    no: "men",
    en: "but",
    pos: "conj",
    examples: [
      { no: "Jeg vil, men kan ikke.", en: "I want to, but I can't." },
      { no: "Han prøvde, men det var vanskelig.", en: "He tried, but it was difficult." }
    ],
    cloze_no: "Jeg vil, ____ kan ikke.",
    cloze_answer: "men"
  },

  {
    no: "hva",
    en: "what",
    pos: "pron",
    examples: [
      { no: "Hva gjør du?", en: "What are you doing?" },
      { no: "Hva heter du?", en: "What is your name?" }
    ],
    cloze_no: "____ gjør du?",
    cloze_answer: "Hva"
  },

  {
    no: "noen",
    en: "someone / some",
    pos: "pron",
    examples: [
      { no: "Noen ringer.", en: "Someone is calling." },
      { no: "Jeg kjenner noen der.", en: "I know someone there." }
    ],
    confusions: ["noe"]
  },

  {
    no: "den",
    en: "that / it",
    pos: "pron",
    examples: [
      { no: "Den er fin.", en: "It is nice." },
      { no: "Den bilen er stor.", en: "That car is big." }
    ],
    cloze_no: "____ er fin.",
    cloze_answer: "Den",
    confusions: ["det", "de"]
  },

  { no: "du", en: "you", pos: "pron", example: "Hvor er du?", example_en: "Where are you?" },
  { no: "eller", en: "or", pos: "conj", example: "Te eller kaffe?", example_en: "Tea or coffee?" },
  { no: "hadde", en: "had", pos: "verb", example: "Jeg hadde en hund.", example_en: "I had a dog." },
  { no: "av", en: "of / by", pos: "prep", example: "En venn av meg.", example_en: "A friend of mine." },
  { no: "til", en: "to", pos: "prep", example: "Jeg går til butikken.", example_en: "I go to the store." },
  { no: "og", en: "and", pos: "conj", example: "Jeg liker kaffe og te.", example_en: "I like coffee and tea." },
  { no: "en", en: "a / one", pos: "article", example: "En bok ligger der.", example_en: "A book lies there." },
  { no: "i", en: "in", pos: "prep", example: "Hun bor i Oslo.", example_en: "She lives in Oslo." },
  { no: "vi", en: "we", pos: "pron", example: "Vi er venner.", example_en: "We are friends." },
  { no: "kan", en: "can", pos: "verb", example: "Jeg kan svømme.", example_en: "I can swim." },
  { no: "ut", en: "out", pos: "adv", example: "Gå ut!", example_en: "Go out!" },
  { no: "andre", en: "other", pos: "adj", example: "Andre mennesker.", example_en: "Other people." },
  { no: "gjøre", en: "to do", pos: "verb", example: "Hva skal vi gjøre?", example_en: "What shall we do?" },
  { no: "deres", en: "their", pos: "pron", example: "Det er deres hus.", example_en: "That is their house." },
  { no: "tid", en: "time", pos: "noun", example: "Jeg har ikke tid.", example_en: "I don't have time." },
  { no: "hvis", en: "if", pos: "conj", example: "Hvis det regner, blir jeg hjemme.", example_en: "If it rains, I stay home." },
  { no: "vil", en: "will / want", pos: "verb", example: "Jeg vil lære.", example_en: "I want to learn." },
  { no: "hvordan", en: "how", pos: "adv", example: "Hvordan går det?", example_en: "How is it going?" },
  { no: "sa", en: "said", pos: "verb", example: "Han sa det.", example_en: "He said it." },
  { no: "hver", en: "each", pos: "det", example: "Hver dag trener jeg.", example_en: "Each day I train." },
  { no: "fortelle", en: "to tell", pos: "verb", example: "Fortell meg sannheten.", example_en: "Tell me the truth." },
  { no: "gjør", en: "does / do", pos: "verb", example: "Hva gjør du?", example_en: "What do you do?" },
  { no: "sett", en: "seen / set", pos: "verb", example: "Jeg har sett filmen.", example_en: "I have seen the movie." },
  { no: "tre", en: "three", pos: "num", example: "Jeg har tre venner.", example_en: "I have three friends." },
  { no: "ønsker", en: "wants", pos: "verb", example: "Hun ønsker hjelp.", example_en: "She wants help." },
  { no: "luft", en: "air", pos: "noun", example: "Frisk luft er godt.", example_en: "Fresh air is good." },
  { no: "godt", en: "good / well", pos: "adv", example: "Det smaker godt.", example_en: "It tastes good." },
  { no: "også", en: "also", pos: "adv", example: "Jeg kommer også.", example_en: "I am coming too." },
  { no: "spille", en: "to play", pos: "verb", example: "Jeg liker å spille.", example_en: "I like to play." },
  { no: "liten", en: "small", pos: "adj", example: "En liten katt.", example_en: "A small cat." },
  { no: "ende", en: "end", pos: "noun", example: "Slutten er nær.", example_en: "The end is near." },
  { no: "sette", en: "to set / put", pos: "verb", example: "Sett det der.", example_en: "Put it there." },
  { no: "hjem", en: "home", pos: "noun", example: "Jeg går hjem.", example_en: "I go home." },
  { no: "lese", en: "to read", pos: "verb", example: "Jeg leser en bok.", example_en: "I read a book." },
  { no: "hånd", en: "hand", pos: "noun", example: "Hold hånden min.", example_en: "Hold my hand." },
  { no: "stor", en: "big", pos: "adj", example: "Et stort hus.", example_en: "A big house." },
  { no: "selv", en: "self", pos: "pron", example: "Jeg gjør det selv.", example_en: "I do it myself." },
  { no: "her", en: "here", pos: "adv", example: "Kom her.", example_en: "Come here." },
  { no: "må", en: "must", pos: "verb", example: "Jeg må gå.", example_en: "I must go." },
  { no: "høy", en: "high", pos: "adj", example: "Et høyt fjell.", example_en: "A high mountain." },
  { no: "slik", en: "such / like this", pos: "det", example: "Gjør det slik.", example_en: "Do it like this." },
  { no: "hvorfor", en: "why", pos: "adv", example: "Hvorfor er du her?", example_en: "Why are you here?" },
  { no: "spør", en: "ask", pos: "verb", example: "Spør læreren.", example_en: "Ask the teacher." },
  { no: "menn", en: "men", pos: "noun", example: "To menn står der.", example_en: "Two men stand there." },
  { no: "gikk", en: "went", pos: "verb", example: "Jeg gikk hjem.", example_en: "I went home." },
  { no: "lys", en: "light", pos: "noun", example: "Lyset er sterkt.", example_en: "The light is strong." },
  { no: "trenger", en: "need", pos: "verb", example: "Jeg trenger hjelp.", example_en: "I need help." },
  { no: "huset", en: "the house", pos: "noun", example: "Huset er stort.", example_en: "The house is big." },
  { no: "bilde", en: "picture", pos: "noun", example: "Et fint bilde.", example_en: "A nice picture." },
  { no: "prøve", en: "to try", pos: "verb", example: "Prøv igjen.", example_en: "Try again." },
  { no: "oss", en: "us", pos: "pron", example: "Bli med oss.", example_en: "Join us." },
  { no: "igjen", en: "again", pos: "adv", example: "Si det igjen.", example_en: "Say it again." },
  { no: "dyr", en: "animal", pos: "noun", example: "Et stort dyr.", example_en: "A big animal." },
  { no: "punkt", en: "point", pos: "noun", example: "Et viktig punkt.", example_en: "An important point." },
  { no: "mor", en: "mother", pos: "noun", example: "Min mor.", example_en: "My mother." },
  { no: "verden", en: "world", pos: "noun", example: "Verden er stor.", example_en: "The world is big." },
  { no: "nær", en: "near", pos: "adv", example: "Kom nær.", example_en: "Come closer." },
  { no: "far", en: "father", pos: "noun", example: "Min far.", example_en: "My father." },
  { no: "ny", en: "new", pos: "adj", example: "En ny bil.", example_en: "A new car." },
  { no: "arbeid", en: "work", pos: "noun", example: "Jeg liker arbeidet.", example_en: "I like the work." },
  { no: "ta", en: "to take", pos: "verb", example: "Ta boken.", example_en: "Take the book." },
  { no: "få", en: "to get", pos: "verb", example: "Jeg får hjelp.", example_en: "I get help." },
  { no: "sted", en: "place", pos: "noun", example: "Et fint sted.", example_en: "A nice place." },
  { no: "leve", en: "to live", pos: "verb", example: "Jeg vil leve her.", example_en: "I want to live here." },
  { no: "tilbake", en: "back", pos: "adv", example: "Kom tilbake.", example_en: "Come back." },
  { no: "bare", en: "only / just", pos: "adv", example: "Jeg er bare trøtt.", example_en: "I am just tired." },
  { no: "mann", en: "man", pos: "noun", example: "En mann går.", example_en: "A man walks." },
  { no: "år", en: "year", pos: "noun", example: "Ett år går fort.", example_en: "A year goes fast." },
  { no: "kom", en: "came", pos: "verb", example: "Han kom hjem.", example_en: "He came home." },
  { no: "alle", en: "all", pos: "pron", example: "Alle er her.", example_en: "Everyone is here." },
  { no: "god", en: "good", pos: "adj", example: "En god dag.", example_en: "A good day." },
  { no: "meg", en: "me", pos: "pron", example: "Gi meg den.", example_en: "Give it to me." },
  { no: "gi", en: "to give", pos: "verb", example: "Gi meg boken.", example_en: "Give me the book." },
  { no: "vår", en: "our", pos: "pron", example: "Dette er vår bil.", example_en: "This is our car." },
  { no: "navn", en: "name", pos: "noun", example: "Hva er ditt navn?", example_en: "What is your name?" },
  { no: "veldig", en: "very", pos: "adv", example: "Det er veldig bra.", example_en: "It is very good." },
  { no: "gjennom", en: "through", pos: "prep", example: "Vi går gjennom byen.", example_en: "We walk through the city." },
  { no: "tror", en: "believe / think", pos: "verb", example: "Jeg tror deg.", example_en: "I believe you." },
  { no: "si", en: "to say", pos: "verb", example: "Hva vil du si?", example_en: "What do you want to say?" },
  { no: "hjelpe", en: "to help", pos: "verb", example: "Kan du hjelpe meg?", example_en: "Can you help me?" },
  { no: "lav", en: "low", pos: "adj", example: "Et lavt nivå.", example_en: "A low level." },
  { no: "mye", en: "much / a lot", pos: "adv", example: "Jeg jobber mye.", example_en: "I work a lot." },
  { no: "før", en: "before", pos: "prep", example: "Før middag.", example_en: "Before dinner." },
  { no: "flytte", en: "to move", pos: "verb", example: "Vi flytter snart.", example_en: "We are moving soon." },
  { no: "høyre", en: "right", pos: "noun", example: "Ta til høyre.", example_en: "Turn right." },
  { no: "gutt", en: "boy", pos: "noun", example: "En liten gutt.", example_en: "A small boy." },
  { no: "gammel", en: "old", pos: "adj", example: "En gammel mann.", example_en: "An old man." },
  { no: "samme", en: "same", pos: "adj", example: "Det er det samme.", example_en: "It is the same." },
  { no: "hun", en: "she", pos: "pron", example: "Hun er glad.", example_en: "She is happy." },
  { no: "når", en: "when", pos: "adv", example: "Når kommer du?", example_en: "When are you coming?" },
  { no: "opp", en: "up", pos: "adv", example: "Stå opp!", example_en: "Stand up!" },
  { no: "bruk", en: "use", pos: "noun", example: "God bruk av tid.", example_en: "Good use of time." },
  { no: "din", en: "your", pos: "pron", example: "Din bil er fin.", example_en: "Your car is nice." },
  { no: "måte", en: "way / method", pos: "noun", example: "En god måte.", example_en: "A good way." },
  { no: "om", en: "about", pos: "prep", example: "Vi snakker om det.", example_en: "We talk about it." },
  { no: "mange", en: "many", pos: "adj", example: "Mange mennesker.", example_en: "Many people." },
  { no: "deretter", en: "after that", pos: "adv", example: "Vi spiser, deretter går vi.", example_en: "We eat, then we go." },
  { no: "dem", en: "them", pos: "pron", example: "Jeg ser dem.", example_en: "I see them." },
  { no: "skrive", en: "to write", pos: "verb", example: "Jeg skriver et brev.", example_en: "I write a letter." },
  { no: "ville", en: "would", pos: "verb", example: "Jeg ville hjelpe.", example_en: "I would help." },
  { no: "så", en: "so / then", pos: "adv", example: "Så vi dro.", example_en: "Then we left." },
  { no: "disse", en: "these", pos: "pron", example: "Disse bøkene.", example_en: "These books." },
  { no: "henne", en: "her", pos: "pron", example: "Jeg kjenner henne.", example_en: "I know her." },
  { no: "lang", en: "long", pos: "adj", example: "En lang vei.", example_en: "A long road." },
  { no: "ting", en: "thing", pos: "noun", example: "En viktig ting.", example_en: "An important thing." },
  { no: "se", en: "to see", pos: "verb", example: "Jeg ser deg.", example_en: "I see you." },
  { no: "ham", en: "him", pos: "pron", example: "Jeg møtte ham.", example_en: "I met him." },
  { no: "to", en: "two", pos: "num", example: "To personer.", example_en: "Two people." },
  { no: "mer", en: "more", pos: "adv", example: "Jeg vil ha mer.", example_en: "I want more." },
  { no: "dag", en: "day", pos: "noun", example: "En fin dag.", example_en: "A nice day." },
  { no: "kunne", en: "could", pos: "verb", example: "Jeg kunne gjøre det.", example_en: "I could do it." },
  { no: "gå", en: "to go", pos: "verb", example: "Vi går nå.", example_en: "We go now." },
  { no: "kommer", en: "comes", pos: "verb", example: "Han kommer snart.", example_en: "He comes soon." },
  { no: "gjorde", en: "did", pos: "verb", example: "Jeg gjorde det.", example_en: "I did it." },
  { no: "nummer", en: "number", pos: "noun", example: "Et nummer.", example_en: "A number." },
  { no: "høres", en: "sounds", pos: "verb", example: "Det høres bra ut.", example_en: "That sounds good." },
  { no: "mest", en: "most", pos: "adv", example: "Jeg liker det mest.", example_en: "I like it most." },
  { no: "folk", en: "people", pos: "noun", example: "Mange folk.", example_en: "Many people." },
  { no: "min", en: "my", pos: "pron", example: "Min bok.", example_en: "My book." },
  { no: "løpet", en: "run / course", pos: "noun", example: "Et langt løp.", example_en: "A long run." },
  { no: "vet", en: "know", pos: "verb", example: "Jeg vet det.", example_en: "I know it." },
  { no: "vann", en: "water", pos: "noun", example: "Drikk vann.", example_en: "Drink water." },
  { no: "enn", en: "than", pos: "conj", example: "Større enn meg.", example_en: "Bigger than me." },
  { no: "første", en: "first", pos: "adj", example: "Min første dag.", example_en: "My first day." },
  { no: "ned", en: "down", pos: "adv", example: "Sett deg ned.", example_en: "Sit down." },
  { no: "side", en: "side", pos: "noun", example: "På den siden.", example_en: "On that side." },
  { no: "vært", en: "been", pos: "verb", example: "Jeg har vært der.", example_en: "I have been there." },
  { no: "nå", en: "now", pos: "adv", example: "Vi drar nå.", example_en: "We leave now." },
  { no: "finne", en: "to find", pos: "verb", example: "Jeg finner den.", example_en: "I find it." },
  { no: "hode", en: "head", pos: "noun", example: "Han rister på hodet.", example_en: "He shakes his head." },
  { no: "stå", en: "to stand", pos: "verb", example: "Stå stille.", example_en: "Stand still." },
  { no: "egen", en: "own", pos: "adj", example: "Min egen bil.", example_en: "My own car." },
  { no: "bør", en: "should", pos: "verb", example: "Du bør gå.", example_en: "You should go." },
  { no: "funnet", en: "found", pos: "verb", example: "Jeg har funnet det.", example_en: "I have found it." },
  { no: "svar", en: "answer", pos: "noun", example: "Et riktig svar.", example_en: "A correct answer." },
  { no: "skole", en: "school", pos: "noun", example: "Barna går på skole.", example_en: "The children go to school." },
  { no: "vokse", en: "to grow", pos: "verb", example: "Barna vokser.", example_en: "The children grow." },
  { no: "lære", en: "to learn", pos: "verb", example: "Jeg lærer norsk.", example_en: "I learn Norwegian." },
  { no: "mat", en: "food", pos: "noun", example: "God mat.", example_en: "Good food." },
  { no: "sol", en: "sun", pos: "noun", example: "Solen skinner.", example_en: "The sun shines." },
  { no: "fire", en: "four", pos: "num", example: "Fire personer.", example_en: "Four people." },
  { no: "mellom", en: "between", pos: "prep", example: "Mellom deg og meg.", example_en: "Between you and me." },
  { no: "holde", en: "to hold", pos: "verb", example: "Hold dette.", example_en: "Hold this." },
  { no: "øye", en: "eye", pos: "noun", example: "Et blått øye.", example_en: "A blue eye." },
  { no: "aldri", en: "never", pos: "adv", example: "Jeg gjør det aldri.", example_en: "I never do that." },
  { no: "siste", en: "last", pos: "adj", example: "Siste gang.", example_en: "Last time." },
  { no: "la", en: "let", pos: "verb", example: "La oss gå.", example_en: "Let us go." },
  { no: "trodde", en: "thought", pos: "verb", example: "Jeg trodde det.", example_en: "I thought that." },
  { no: "by", en: "city", pos: "noun", example: "En stor by.", example_en: "A big city." },
  { no: "krysse", en: "to cross", pos: "verb", example: "Kryss veien.", example_en: "Cross the road." },
  { no: "gård", en: "farm", pos: "noun", example: "En liten gård.", example_en: "A small farm." },
  { no: "vanskelig", en: "difficult", pos: "adj", example: "Det er vanskelig.", example_en: "It is difficult." },
  { no: "start", en: "start", pos: "noun", example: "En god start.", example_en: "A good start." },
  { no: "kanskje", en: "maybe", pos: "adv", example: "Kanskje senere.", example_en: "Maybe later." },
  { no: "historie", en: "history / story", pos: "noun", example: "En lang historie.", example_en: "A long story." },
  { no: "sag", en: "saw", pos: "noun", example: "Han bruker en sag i hagen.", example_en: "He uses a saw in the garden." },
  { no: "langt", en: "far / a long way", pos: "adv", example: "Det er langt hjem.", example_en: "It is a long way home." },
  { no: "tegne", en: "to draw", pos: "verb", example: "Barnet liker å tegne.", example_en: "The child likes to draw." },
  { no: "venstre", en: "left", pos: "noun", example: "Ta til venstre her.", example_en: "Turn left here." },
  { no: "sent", en: "late", pos: "adj", example: "Det er sent nå.", example_en: "It is late now." },
  { no: "kjøre", en: "to drive", pos: "verb", example: "Jeg kjører til byen.", example_en: "I drive to the city." },
  { no: "mens", en: "while", pos: "conj", example: "Jeg leste mens hun skrev.", example_en: "I read while she wrote." },
  { no: "trykk", en: "pressure / press", pos: "noun", example: "Det er mye trykk på jobben.", example_en: "There is a lot of pressure at work." },
  { no: "natt", en: "night", pos: "noun", example: "Det var en kald natt.", example_en: "It was a cold night." },
  { no: "livet", en: "life", pos: "noun", example: "Livet er ikke alltid lett.", example_en: "Life is not always easy." },
  { no: "nord", en: "north", pos: "noun", example: "Vi reiser nord i sommer.", example_en: "We are traveling north this summer." },
  { no: "bok", en: "book", pos: "noun", example: "Jeg leser en bok.", example_en: "I am reading a book." },
  { no: "bære", en: "to carry", pos: "verb", example: "Kan du bære denne vesken?", example_en: "Can you carry this bag?" },
  { no: "tok", en: "took", pos: "verb", example: "Hun tok bussen hjem.", example_en: "She took the bus home." },
  { no: "vitenskap", en: "science", pos: "noun", example: "Han studerer vitenskap.", example_en: "He studies science." },
  { no: "spise", en: "to eat", pos: "verb", example: "Vi skal spise snart.", example_en: "We are going to eat soon." },
  { no: "rom", en: "room / space", pos: "noun", example: "Det er mye rom her.", example_en: "There is a lot of space here." },
  { no: "venn", en: "friend", pos: "noun", example: "Hun er en god venn.", example_en: "She is a good friend." },
  { no: "begynte", en: "began", pos: "verb", example: "Han begynte tidlig i dag.", example_en: "He started early today." },
  { no: "idé", en: "idea", pos: "noun", example: "Det var en god idé.", example_en: "That was a good idea." },
  { no: "fisk", en: "fish", pos: "noun", example: "Vi spiser fisk til middag.", example_en: "We are eating fish for dinner." },
  { no: "fjellet", en: "the mountain", pos: "noun", example: "Snøen ligger på fjellet.", example_en: "The snow lies on the mountain." },
  { no: "stoppe", en: "to stop", pos: "verb", example: "Bussen stopper her.", example_en: "The bus stops here." },
  { no: "gang", en: "time / occasion", pos: "noun", example: "Neste gang blir jeg med.", example_en: "Next time I will join." },
  { no: "basen", en: "the base", pos: "noun", example: "Soldatene kom tilbake til basen.", example_en: "The soldiers returned to the base." },
  { no: "høre", en: "to hear", pos: "verb", example: "Kan du høre meg?", example_en: "Can you hear me?" },
  { no: "hest", en: "horse", pos: "noun", example: "Hun rir på en hest.", example_en: "She rides a horse." },
  { no: "kutt", en: "cut", pos: "noun", example: "Han fikk et lite kutt i hånden.", example_en: "He got a small cut on his hand." },
  { no: "sikker", en: "sure / safe", pos: "adj", example: "Er du sikker på det?", example_en: "Are you sure about that?" },
  { no: "farge", en: "color", pos: "noun", example: "Hva er din favorittfarge?", example_en: "What is your favorite color?" },
  { no: "ansikt", en: "face", pos: "noun", example: "Hun hadde et glad ansikt.", example_en: "She had a happy face." },
  { no: "hoved", en: "main / head", pos: "noun", example: "Dette er hovedideen.", example_en: "This is the main idea." },
  { no: "åpent", en: "open", pos: "adj", example: "Butikken er åpen nå.", example_en: "The store is open now." },
  { no: "synes", en: "think / find", pos: "verb", example: "Jeg synes filmen var bra.", example_en: "I think the movie was good." },
  { no: "sammen", en: "together", pos: "adv", example: "Vi jobber sammen.", example_en: "We work together." },
  { no: "neste", en: "next", pos: "adj", example: "Vi sees neste uke.", example_en: "We will see each other next week." },
  { no: "hvit", en: "white", pos: "adj", example: "Hun har en hvit jakke.", example_en: "She has a white jacket." },
  { no: "barn", en: "child / children", pos: "noun", example: "Barn leker ute.", example_en: "Children are playing outside." },
  { no: "begynne", en: "to begin", pos: "verb", example: "La oss begynne nå.", example_en: "Let us begin now." },
  { no: "fikk", en: "got / received", pos: "verb", example: "Jeg fikk en melding.", example_en: "I got a message." },
  { no: "eksempel", en: "example", pos: "noun", example: "Kan du gi et eksempel?", example_en: "Can you give an example." },
  { no: "lette", en: "light / easy", pos: "adj", example: "Dette er en lett oppgave.", example_en: "This is an easy task." },
  { no: "papir", en: "paper", pos: "noun", example: "Skriv det på papir.", example_en: "Write it on paper." },
  { no: "gruppe", en: "group", pos: "noun", example: "Vi jobber i en gruppe.", example_en: "We work in a group." },
  { no: "alltid", en: "always", pos: "adv", example: "Hun kommer alltid tidlig.", example_en: "She always comes early." },
  { no: "musikk", en: "music", pos: "noun", example: "Jeg liker rolig musikk.", example_en: "I like calm music." },
  { no: "både", en: "both", pos: "conj", example: "Jeg liker både te og kaffe.", example_en: "I like both tea and coffee." },
  { no: "mark", en: "field / ground", pos: "noun", example: "Barna løper over marken.", example_en: "The children run across the field." },
  { no: "ofte", en: "often", pos: "adv", example: "Jeg trener ofte.", example_en: "I train often." },
  { no: "brev", en: "letter", pos: "noun", example: "Hun skrev et brev.", example_en: "She wrote a letter." },
  { no: "elv", en: "river", pos: "noun", example: "Vi gikk langs elven.", example_en: "We walked along the river." },
  { no: "bil", en: "car", pos: "noun", example: "Han har en ny bil.", example_en: "He has a new car." },
  { no: "føtter", en: "feet", pos: "noun", example: "Jeg er kald på føttene.", example_en: "My feet are cold." },
  { no: "omsorg", en: "care", pos: "noun", example: "Barn trenger omsorg.", example_en: "Children need care." },
  { no: "nok", en: "enough", pos: "adv", example: "Det er nok mat til alle.", example_en: "There is enough food for everyone." },
  { no: "jente", en: "girl", pos: "noun", example: "En liten jente står der.", example_en: "A little girl stands there." },
  { no: "vanlig", en: "usual / common", pos: "adj", example: "Det er helt vanlig.", example_en: "That is completely normal." },
  { no: "ung", en: "young", pos: "adj", example: "Han er fortsatt ung.", example_en: "He is still young." },
  { no: "klar", en: "ready / clear", pos: "adj", example: "Jeg er klar nå.", example_en: "I am ready now." },
  { no: "ovenfor", en: "above", pos: "prep", example: "Bildet henger ovenfor sengen.", example_en: "The picture hangs above the bed." },
  { no: "noensinne", en: "ever", pos: "adv", example: "Har du noensinne vært der?", example_en: "Have you ever been there?" },
  { no: "liste", en: "list", pos: "noun", example: "Jeg skrev en liste.", example_en: "I wrote a list." },
  { no: "skjønt", en: "although / understood", pos: "conj", example: "Det er vanskelig, skjønt mulig.", example_en: "It is difficult, although possible." },
  { no: "føler", en: "feel", pos: "verb", example: "Jeg føler meg bedre i dag.", example_en: "I feel better today." },
  { no: "diskusjon", en: "discussion", pos: "noun", example: "Vi hadde en lang diskusjon.", example_en: "We had a long discussion." },
  { no: "fugl", en: "bird", pos: "noun", example: "En fugl sitter i treet.", example_en: "A bird is sitting in the tree." },
  { no: "snart", en: "soon", pos: "adv", example: "Vi ses snart.", example_en: "See you soon." },
  { no: "kroppen", en: "the body", pos: "noun", example: "Kroppen trenger hvile.", example_en: "The body needs rest." },
  { no: "hund", en: "dog", pos: "noun", example: "Naboen har en hund.", example_en: "The neighbor has a dog." },
  { no: "familie", en: "family", pos: "noun", example: "Jeg besøker familien min.", example_en: "I am visiting my family." },
  { no: "direkte", en: "directly / direct", pos: "adv", example: "Flyet går direkte til Oslo.", example_en: "The flight goes directly to Oslo." },
  { no: "forlate", en: "to leave", pos: "verb", example: "Vi må forlate huset nå.", example_en: "We must leave the house now." },
  { no: "sangen", en: "the song", pos: "noun", example: "Jeg liker sangen godt.", example_en: "I like the song a lot." },
  { no: "måle", en: "to measure", pos: "verb", example: "Vi må måle bordet.", example_en: "We need to measure the table." },
  { no: "dør", en: "door", pos: "noun", example: "Lukk døren, vær så snill.", example_en: "Close the door, please." },
  { no: "produkt", en: "product", pos: "noun", example: "Dette er et nytt produkt.", example_en: "This is a new product." },
  { no: "svart", en: "black", pos: "adj", example: "Han har en svart bil.", example_en: "He has a black car." },
  { no: "kort", en: "short / card", pos: "adj", example: "Det var en kort samtale.", example_en: "It was a short conversation." },
  { no: "tall", en: "number", pos: "noun", example: "Skriv riktig tall.", example_en: "Write the correct number." },
  { no: "klasse", en: "class", pos: "noun", example: "Hun går i samme klasse som meg.", example_en: "She is in the same class as me." },
  { no: "vind", en: "wind", pos: "noun", example: "Det er mye vind i dag.", example_en: "There is a lot of wind today." },
  { no: "spørsmål", en: "question", pos: "noun", example: "Jeg har et spørsmål.", example_en: "I have a question." },
  { no: "skje", en: "to happen", pos: "verb", example: "Hva skal skje nå?", example_en: "What is going to happen now?" },
  { no: "komplett", en: "complete", pos: "adj", example: "Oppgaven er nå komplett.", example_en: "The task is now complete." },
  { no: "skip", en: "ship", pos: "noun", example: "Et stort skip kom inn i havnen.", example_en: "A large ship came into the harbor." },
  { no: "område", en: "area", pos: "noun", example: "Dette er et stille område.", example_en: "This is a quiet area." },
  { no: "halv", en: "half", pos: "adj", example: "Jeg spiste en halv pizza.", example_en: "I ate half a pizza." },
  { no: "stein", en: "stone", pos: "noun", example: "Barnet kastet en stein.", example_en: "The child threw a stone." },
  { no: "rekkefølge", en: "order / sequence", pos: "noun", example: "Sett dem i riktig rekkefølge.", example_en: "Put them in the correct order." },
  { no: "brann", en: "fire", pos: "noun", example: "Brannen startet i natt.", example_en: "The fire started at night." },
  { no: "sør", en: "south", pos: "noun", example: "De bor sør i landet.", example_en: "They live in the south of the country." },
  { no: "problem", en: "problem", pos: "noun", example: "Vi må løse dette problemet.", example_en: "We need to solve this problem." },
  { no: "fortalte", en: "told", pos: "verb", example: "Hun fortalte meg alt.", example_en: "She told me everything." },
  { no: "visste", en: "knew", pos: "verb", example: "Jeg visste svaret.", example_en: "I knew the answer." },
  { no: "passere", en: "to pass", pos: "verb", example: "Vi må passere broen.", example_en: "We have to pass the bridge." },
  { no: "siden", en: "since", pos: "prep", example: "Jeg har bodd her siden 2020.", example_en: "I have lived here since 2020." },
  { no: "toppen", en: "the top", pos: "noun", example: "Vi nådde toppen av fjellet.", example_en: "We reached the top of the mountain." },
  { no: "hele", en: "whole / entire", pos: "adj", example: "Jeg leste hele boken.", example_en: "I read the whole book." },
  { no: "ingenting", en: "nothing", pos: "pron", example: "Jeg ser ingenting.", example_en: "I see nothing." },
  { no: "kurs", en: "course", pos: "noun", example: "Jeg tar et kurs i norsk.", example_en: "I take a course in Norwegian." },
  { no: "opphold", en: "stay", pos: "noun", example: "Vi hadde et kort opphold.", example_en: "We had a short stay." },
  { no: "fullt", en: "full", pos: "adj", example: "Glasset er fullt.", example_en: "The glass is full." },
  { no: "kraft", en: "power", pos: "noun", example: "Han har mye kraft.", example_en: "He has a lot of power." },
  { no: "blå", en: "blue", pos: "adj", example: "Himmelen er blå.", example_en: "The sky is blue." },
  { no: "objekt", en: "object", pos: "noun", example: "Et tungt objekt.", example_en: "A heavy object." },
  { no: "bestemme", en: "to decide", pos: "verb", example: "Vi må bestemme oss.", example_en: "We must decide." },
  { no: "overflaten", en: "the surface", pos: "noun", example: "Vannet er rolig på overflaten.", example_en: "The water is calm on the surface." },
  { no: "dyp", en: "deep", pos: "adj", example: "En dyp innsjø.", example_en: "A deep lake." },
  { no: "månen", en: "the moon", pos: "noun", example: "Månen lyser i natt.", example_en: "The moon shines tonight." },
  { no: "øy", en: "island", pos: "noun", example: "Vi besøker en øy.", example_en: "We visit an island." },
  { no: "foten", en: "the foot", pos: "noun", example: "Han skadet foten.", example_en: "He injured his foot." },
  { no: "system", en: "system", pos: "noun", example: "Systemet fungerer godt.", example_en: "The system works well." },
  { no: "opptatt", en: "busy", pos: "adj", example: "Jeg er opptatt i dag.", example_en: "I am busy today." },
  { no: "test", en: "test", pos: "noun", example: "Vi har en test i morgen.", example_en: "We have a test tomorrow." },
  { no: "rekord", en: "record", pos: "noun", example: "Han satte en rekord.", example_en: "He set a record." },
  { no: "båt", en: "boat", pos: "noun", example: "Vi tok en båt.", example_en: "We took a boat." },
  { no: "felles", en: "common / shared", pos: "adj", example: "Vi har et felles mål.", example_en: "We have a common goal." },
  { no: "gull", en: "gold", pos: "noun", example: "Hun vant gull.", example_en: "She won gold." },
  { no: "mulig", en: "possible", pos: "adj", example: "Alt er mulig.", example_en: "Everything is possible." },
  { no: "planet", en: "planet", pos: "noun", example: "Jorden er en planet.", example_en: "Earth is a planet." },
  { no: "stedet", en: "the place", pos: "noun", example: "Dette er stedet.", example_en: "This is the place." },
  { no: "rart", en: "strange", pos: "adj", example: "Det er rart.", example_en: "It is strange." },
  { no: "latter", en: "laughter", pos: "noun", example: "Rommet var fylt med latter.", example_en: "The room was filled with laughter." },
  { no: "tusen", en: "thousand", pos: "num", example: "Tusen takk!", example_en: "Thank you very much!" },
  { no: "sjekk", en: "check", pos: "noun", example: "Gjør en sjekk først.", example_en: "Do a check first." },
  { no: "spill", en: "game", pos: "noun", example: "Vi spiller et spill.", example_en: "We play a game." },
  { no: "form", en: "form / shape", pos: "noun", example: "En enkel form.", example_en: "A simple shape." },
  { no: "savner", en: "miss", pos: "verb", example: "Jeg savner deg.", example_en: "I miss you." },
  { no: "brakte", en: "brought", pos: "verb", example: "Han brakte gaven.", example_en: "He brought the gift." },
  { no: "snø", en: "snow", pos: "noun", example: "Det faller snø.", example_en: "Snow is falling." },
  { no: "bringe", en: "to bring", pos: "verb", example: "Kan du bringe det?", example_en: "Can you bring it?" },
  { no: "ja", en: "yes", pos: "interj", example: "Ja, jeg kommer.", example_en: "Yes, I am coming." },
  { no: "fjernt", en: "distant", pos: "adj", example: "Et fjernt sted.", example_en: "A distant place." },
  { no: "fylle", en: "to fill", pos: "verb", example: "Fyll glasset.", example_en: "Fill the glass." },
  { no: "øst", en: "east", pos: "noun", example: "Solen står opp i øst.", example_en: "The sun rises in the east." },
  { no: "maling", en: "paint", pos: "noun", example: "Vi kjøper maling.", example_en: "We buy paint." },
  { no: "språk", en: "language", pos: "noun", example: "Norsk er et språk.", example_en: "Norwegian is a language." },
  { no: "blant", en: "among", pos: "prep", example: "Blant vennene mine.", example_en: "Among my friends." },
  { no: "enhet", en: "unit", pos: "noun", example: "En måleenhet.", example_en: "A unit of measurement." },
  { no: "makt", en: "power", pos: "noun", example: "Han har makt.", example_en: "He has power." },
  { no: "byen", en: "the city", pos: "noun", example: "Byen er stor.", example_en: "The city is big." },
  { no: "viss", en: "certain", pos: "adj", example: "Jeg er viss på det.", example_en: "I am certain about it." },
  { no: "fly", en: "plane", pos: "noun", example: "Flyet lander snart.", example_en: "The plane lands soon." },
  { no: "høst", en: "autumn", pos: "noun", example: "Jeg liker høst.", example_en: "I like autumn." },
  { no: "føre", en: "to lead", pos: "verb", example: "Han fører gruppen.", example_en: "He leads the group." },
  { no: "gråte", en: "to cry", pos: "verb", example: "Barnet begynte å gråte.", example_en: "The child started to cry." },
  { no: "mørk", en: "dark", pos: "adj", example: "Det er mørkt ute.", example_en: "It is dark outside." },
  { no: "maskin", en: "machine", pos: "noun", example: "En stor maskin.", example_en: "A big machine." },
  { no: "notat", en: "note", pos: "noun", example: "Jeg skrev et notat.", example_en: "I wrote a note." },
  { no: "vente", en: "to wait", pos: "verb", example: "Vent litt.", example_en: "Wait a moment." },
  { no: "plan", en: "plan", pos: "noun", example: "Vi har en plan.", example_en: "We have a plan." },
  { no: "figur", en: "figure", pos: "noun", example: "En enkel figur.", example_en: "A simple figure." },
  { no: "boks", en: "box", pos: "noun", example: "Legg det i en boks.", example_en: "Put it in a box." },
  { no: "felt", en: "field", pos: "noun", example: "Et stort felt.", example_en: "A large field." },
  { no: "resten", en: "the rest", pos: "noun", example: "Ta resten.", example_en: "Take the rest." },
  { no: "riktig", en: "correct", pos: "adj", example: "Det er riktig.", example_en: "That is correct." },
  { no: "stand", en: "condition", pos: "noun", example: "God stand.", example_en: "Good condition." },
  { no: "uke", en: "week", pos: "noun", example: "En uke går fort.", example_en: "A week goes fast." },
  { no: "endelig", en: "finally", pos: "adv", example: "Endelig er vi her.", example_en: "Finally we are here." },
  { no: "ga", en: "gave", pos: "verb", example: "Hun ga meg en bok.", example_en: "She gave me a book." },
  { no: "grønn", en: "green", pos: "adj", example: "Et grønt tre.", example_en: "A green tree." },
  { no: "rask", en: "fast", pos: "adj", example: "En rask bil.", example_en: "A fast car." },
  { no: "utvikle", en: "to develop", pos: "verb", example: "Vi utvikler nye ideer.", example_en: "We develop new ideas." },
  { no: "minutt", en: "minute", pos: "noun", example: "Vent ett minutt.", example_en: "Wait one minute." },
  { no: "sterk", en: "strong", pos: "adj", example: "Han er sterk.", example_en: "He is strong." },
  { no: "spesiell", en: "special", pos: "adj", example: "En spesiell dag.", example_en: "A special day." },
  { no: "sinn", en: "mind", pos: "noun", example: "Et rolig sinn.", example_en: "A calm mind." },
  { no: "bak", en: "behind", pos: "prep", example: "Han står bak meg.", example_en: "He stands behind me." },
  { no: "hale", en: "tail", pos: "noun", example: "Hunden har en hale.", example_en: "The dog has a tail." },
  { no: "produsere", en: "to produce", pos: "verb", example: "Fabrikken produserer varer.", example_en: "The factory produces goods." },
  { no: "faktisk", en: "actually", pos: "adv", example: "Det er faktisk sant.", example_en: "It is actually true." },
  { no: "plass", en: "place / space", pos: "noun", example: "Det er plass her.", example_en: "There is space here." },
  { no: "beste", en: "best", pos: "adj", example: "Min beste venn.", example_en: "My best friend." },
  { no: "time", en: "hour / lesson", pos: "noun", example: "Vi har en time nå.", example_en: "We have a lesson now." },
  { no: "bedre", en: "better", pos: "adj", example: "Dette er bedre.", example_en: "This is better." },
  { no: "under", en: "under", pos: "prep", example: "Boken ligger under bordet.", example_en: "The book lies under the table." },
  { no: "hundre", en: "hundred", pos: "num", example: "Hundre kroner.", example_en: "One hundred kroner." },
  { no: "fem", en: "five", pos: "num", example: "Fem personer.", example_en: "Five people." },
  { no: "huske", en: "to remember", pos: "verb", example: "Husk dette.", example_en: "Remember this." },
  { no: "trinn", en: "step", pos: "noun", example: "Ta ett trinn av gangen.", example_en: "Take one step at a time." },
  { no: "tidlig", en: "early", pos: "adj", example: "Jeg står opp tidlig.", example_en: "I wake up early." },
  { no: "holde", en: "to keep / hold", pos: "verb", example: "Hold døren åpen.", example_en: "Keep the door open." },
  { no: "vest", en: "west", pos: "noun", example: "Solen går ned i vest.", example_en: "The sun sets in the west." },
  { no: "bakken", en: "the ground", pos: "noun", example: "Han falt på bakken.", example_en: "He fell on the ground." },
  { no: "interesse", en: "interest", pos: "noun", example: "Jeg har stor interesse for språk.", example_en: "I have great interest in languages." },
  { no: "verb", en: "verb", pos: "noun", example: "Et verb beskriver en handling.", example_en: "A verb describes an action." },
  { no: "synge", en: "to sing", pos: "verb", example: "Hun liker å synge.", example_en: "She likes to sing." },
  { no: "lytte", en: "to listen", pos: "verb", example: "Lytt nøye.", example_en: "Listen carefully." },
  { no: "seks", en: "six", pos: "num", example: "Klokken er seks.", example_en: "It is six o'clock." },
  { no: "bord", en: "table", pos: "noun", example: "Vi sitter ved bordet.", example_en: "We sit at the table." },
  { no: "reise", en: "to travel", pos: "verb", example: "Jeg vil reise.", example_en: "I want to travel." },
  { no: "mindre", en: "less", pos: "adj", example: "Jeg vil ha mindre kaffe.", example_en: "I want less coffee." },
  { no: "morgen", en: "morning", pos: "noun", example: "God morgen!", example_en: "Good morning!" },
  { no: "ti", en: "ten", pos: "num", example: "Ti personer kom.", example_en: "Ten people came." },
  { no: "enkel", en: "simple", pos: "adj", example: "Det er enkelt.", example_en: "It is simple." },
  { no: "flere", en: "several / more", pos: "adj", example: "Flere mennesker kom.", example_en: "Several people came." },
  { no: "vokal", en: "vowel", pos: "noun", example: "A er en vokal.", example_en: "A is a vowel." },
  { no: "mot", en: "against / toward", pos: "prep", example: "Han gikk mot døren.", example_en: "He walked toward the door." },
  { no: "krig", en: "war", pos: "noun", example: "Krigen var lang.", example_en: "The war was long." },
  { no: "lå", en: "lay / was lying", pos: "verb", example: "Boken lå på bordet.", example_en: "The book lay on the table." },
  { no: "mønster", en: "pattern", pos: "noun", example: "Et fint mønster.", example_en: "A nice pattern." },
  { no: "langsom", en: "slow", pos: "adj", example: "En langsom bil.", example_en: "A slow car." },
  { no: "senter", en: "center", pos: "noun", example: "Vi møtes i sentrum.", example_en: "We meet in the center." },
  { no: "elsker", en: "love", pos: "verb", example: "Jeg elsker deg.", example_en: "I love you." },
  { no: "personer", en: "people", pos: "noun", example: "Mange personer kom.", example_en: "Many people came." },
  { no: "penger", en: "money", pos: "noun", example: "Jeg trenger penger.", example_en: "I need money." },
  { no: "tjene", en: "to earn", pos: "verb", example: "Han tjener mye.", example_en: "He earns a lot." },
  { no: "vei", en: "road / way", pos: "noun", example: "Dette er riktig vei.", example_en: "This is the right way." },
  { no: "kart", en: "map", pos: "noun", example: "Se på kartet.", example_en: "Look at the map." },
  { no: "regn", en: "rain", pos: "noun", example: "Det kommer regn.", example_en: "Rain is coming." },
  { no: "regel", en: "rule", pos: "noun", example: "Følg regelen.", example_en: "Follow the rule." },
  { no: "trekke", en: "to pull / draw", pos: "verb", example: "Trekk døren.", example_en: "Pull the door." },
  { no: "kaldt", en: "cold", pos: "adj", example: "Det er kaldt.", example_en: "It is cold." },
  { no: "varsel", en: "warning", pos: "noun", example: "Vi fikk et varsel.", example_en: "We got a warning." },
  { no: "stemme", en: "voice", pos: "noun", example: "Hun har en fin stemme.", example_en: "She has a nice voice." },
  { no: "energi", en: "energy", pos: "noun", example: "Jeg har mye energi.", example_en: "I have a lot of energy." },
  { no: "jakt", en: "hunt", pos: "noun", example: "De er på jakt.", example_en: "They are hunting." },
  { no: "sannsynlig", en: "likely", pos: "adj", example: "Det er sannsynlig.", example_en: "It is likely." },
  { no: "seng", en: "bed", pos: "noun", example: "Jeg går til sengs.", example_en: "I go to bed." },
  { no: "bror", en: "brother", pos: "noun", example: "Min bror bor her.", example_en: "My brother lives here." },
  { no: "egg", en: "egg", pos: "noun", example: "Jeg spiser egg.", example_en: "I eat eggs." },
  { no: "celle", en: "cell", pos: "noun", example: "En biologisk celle.", example_en: "A biological cell." },
  { no: "plukke", en: "to pick", pos: "verb", example: "Plukk blomster.", example_en: "Pick flowers." },
  { no: "teller", en: "counts", pos: "verb", example: "Hun teller til ti.", example_en: "She counts to ten." },
  { no: "grunn", en: "reason / ground", pos: "noun", example: "Hva er grunnen?", example_en: "What is the reason?" },
  { no: "lengde", en: "length", pos: "noun", example: "Mål lengden.", example_en: "Measure the length." },
  { no: "kunst", en: "art", pos: "noun", example: "Jeg liker kunst.", example_en: "I like art." },
  { no: "region", en: "region", pos: "noun", example: "En stor region.", example_en: "A large region." },
  { no: "størrelse", en: "size", pos: "noun", example: "Hva er størrelsen?", example_en: "What is the size?" },
  { no: "variere", en: "to vary", pos: "verb", example: "Resultatene varierer.", example_en: "The results vary." },
  { no: "snakke", en: "to speak", pos: "verb", example: "Vi snakker norsk.", example_en: "We speak Norwegian." },
  { no: "vekt", en: "weight", pos: "noun", example: "Hva er vekten?", example_en: "What is the weight?" },
  { no: "generell", en: "general", pos: "adj", example: "En generell regel.", example_en: "A general rule." },
  { no: "is", en: "ice", pos: "noun", example: "Isen smelter.", example_en: "The ice melts." },
  { no: "sak", en: "case / matter", pos: "noun", example: "Dette er en viktig sak.", example_en: "This is an important matter." },
  { no: "sirkel", en: "circle", pos: "noun", example: "Tegn en sirkel.", example_en: "Draw a circle." },
  { no: "inkludere", en: "to include", pos: "verb", example: "Listen inkluderer alt.", example_en: "The list includes everything." },
  { no: "dele", en: "to divide / share", pos: "verb", example: "Vi deler maten.", example_en: "We share the food." },
  { no: "stavelse", en: "syllable", pos: "noun", example: "Ordet har to stavelser.", example_en: "The word has two syllables." },
  { no: "følte", en: "felt", pos: "verb", example: "Jeg følte meg bra.", example_en: "I felt good." },
  { no: "ball", en: "ball", pos: "noun", example: "Barnet leker med en ball.", example_en: "The child plays with a ball." },
  { no: "ennå", en: "yet", pos: "adv", example: "Ikke ennå.", example_en: "Not yet." },
  { no: "slipp", en: "let go", pos: "verb", example: "Slipp den.", example_en: "Let it go." },
  { no: "hjerte", en: "heart", pos: "noun", example: "Et godt hjerte.", example_en: "A good heart." },
  { no: "tung", en: "heavy", pos: "adj", example: "En tung bag.", example_en: "A heavy bag." },
  { no: "dans", en: "dance", pos: "noun", example: "De danser.", example_en: "They dance." },
  { no: "motor", en: "engine", pos: "noun", example: "Motoren er sterk.", example_en: "The engine is strong." },
  { no: "stilling", en: "position", pos: "noun", example: "En ny stilling.", example_en: "A new position." },
  { no: "arm", en: "arm", pos: "noun", example: "Han løftet armen.", example_en: "He raised his arm." },
  { no: "seil", en: "sail", pos: "noun", example: "Båten har seil.", example_en: "The boat has sails." },
  { no: "materiale", en: "material", pos: "noun", example: "Sterkt materiale.", example_en: "Strong material." },
  { no: "skog", en: "forest", pos: "noun", example: "Vi går i skogen.", example_en: "We walk in the forest." },
  { no: "sitte", en: "to sit", pos: "verb", example: "Sitt ned.", example_en: "Sit down." },
  { no: "vindu", en: "window", pos: "noun", example: "Åpne vinduet.", example_en: "Open the window." },
  { no: "sommer", en: "summer", pos: "noun", example: "Jeg elsker sommer.", example_en: "I love summer." },
  { no: "tog", en: "train", pos: "noun", example: "Toget går nå.", example_en: "The train leaves now." },
  { no: "søvn", en: "sleep", pos: "noun", example: "Jeg trenger søvn.", example_en: "I need sleep." },
  { no: "bevise", en: "to prove", pos: "verb", example: "Han vil bevise det.", example_en: "He wants to prove it." },

  {
    no: "det",
    en: "it / that",
    pos: "pron",
    examples: [
      { no: "Det er kaldt ute.", en: "It is cold outside." },
      { no: "Det er sant.", en: "That is true." },
      { no: "Det går bra.", en: "It is going well." }
    ],
    confusions: ["den", "de"]
  },
  {
    no: "det går bra",
    en: "it is going well",
    pos: "phrase",
    examples: [
      { no: "Når noen spør, kan du si: det går bra.", en: "When someone asks, you can say: it is going well." },
      { no: "Alt går bra nå.", en: "Everything is going well now." }
    ]
  },
  {
    no: "hva gjør du",
    en: "what are you doing",
    pos: "phrase",
    examples: [
      { no: "Hei, hva gjør du?", en: "Hi, what are you doing?" },
      { no: "Jeg spør bare: hva gjør du?", en: "I am just asking: what are you doing?" }
    ]
  }
];