export const WORDS = [
  { no: "som", en: "as / which / who", pos: "conj", example: "Mannen som står der.", example_en: "The man who stands there." },
  { no: "jeg", en: "I", pos: "pron", example: "Jeg er trøtt.", example_en: "I am tired." },
  { no: "hans", en: "his", pos: "pron", example: "Det er hans bok.", example_en: "That is his book." },
  { no: "at", en: "that", pos: "conj", example: "Jeg vet at du kommer.", example_en: "I know that you are coming." },
  { no: "han", en: "he", pos: "pron", example: "Han er lærer.", example_en: "He is a teacher." },
  { no: "var", en: "was / were", pos: "verb", example: "Det var gøy.", example_en: "It was fun." },
  { no: "for", en: "for / because", pos: "prep", example: "Dette er for deg.", example_en: "This is for you." },
  { no: "på", en: "on / at", pos: "prep", example: "Boken ligger på bordet.", example_en: "The book is on the table." },
  { no: "er", en: "is / are / am", pos: "verb", example: "Hun er hjemme.", example_en: "She is at home." },
  { no: "med", en: "with", pos: "prep", example: "Jeg går med deg.", example_en: "I go with you." },
  { no: "de", en: "they", pos: "pron", example: "De kommer snart.", example_en: "They are coming soon." },
  { no: "være", en: "to be", pos: "verb", example: "Å være glad er viktig.", example_en: "To be happy is important." },
  { no: "ett", en: "one", pos: "num", example: "Jeg har ett spørsmål.", example_en: "I have one question." },
  { no: "har", en: "have / has", pos: "verb", example: "Jeg har en bil.", example_en: "I have a car." },
  { no: "dette", en: "this", pos: "pron", example: "Dette er bra.", example_en: "This is good." },
  { no: "fra", en: "from", pos: "prep", example: "Jeg er fra Norge.", example_en: "I am from Norway." },
  { no: "etter", en: "after", pos: "prep", example: "Etter jobb drar jeg hjem.", example_en: "After work I go home." },
  { no: "varm", en: "warm", pos: "adj", example: "Maten er varm.", example_en: "The food is warm." },
  { no: "ordet", en: "the word", pos: "noun", example: "Jeg forstår ordet.", example_en: "I understand the word." },
  { no: "men", en: "but", pos: "conj", example: "Jeg vil, men kan ikke.", example_en: "I want to, but can't." },
  { no: "hva", en: "what", pos: "pron", example: "Hva gjør du?", example_en: "What are you doing?" },
  { no: "noen", en: "someone / some", pos: "pron", example: "Noen ringer.", example_en: "Someone is calling." },
  { no: "den", en: "that / it", pos: "pron", example: "Den er fin.", example_en: "It is nice." },
  { no: "du", en: "you", pos: "pron", example: "Hvor er du?", example_en: "Where are you?" },
  { no: "eller", en: "or", pos: "conj", example: "Te eller kaffe?", example_en: "Tea or coffee?" },
  { no: "hadde", en: "had", pos: "verb", example: "Jeg hadde en hund.", example_en: "I had a dog." },
  { no: "av", en: "of / by", pos: "prep", example: "En venn av meg.", example_en: "A friend of mine." },
  { no: "til", en: "to", pos: "prep", example: "Jeg går til butikken.", example_en: "I go to the store." },
  { no: "og", en: "and", pos: "conj", example: "Jeg liker kaffe og te.", example_en: "I like coffee and tea." },
  { no: "en", en: "a / one", pos: "article", example: "En bok ligger der.", example_en: "A book lies there." },
  { no: "i", en: "in", pos: "prep", example: "Hun bor i Oslo.", example_en: "She lives in Oslo." },
  { no: "vi", en: "we", pos: "pron", example: "Vi er venner.", example_en: "We are friends." },
  { no: "kan", en: "can", pos: "verb", example: "Jeg kan svømme.", example_en: "I can swim." },
  { no: "ut", en: "out", pos: "adv", example: "Gå ut!", example_en: "Go out!" },
  { no: "andre", en: "other", pos: "adj", example: "Andre mennesker.", example_en: "Other people." },
  { no: "gjøre", en: "to do", pos: "verb", example: "Hva skal vi gjøre?", example_en: "What shall we do?" },
  { no: "deres", en: "their", pos: "pron", example: "Det er deres hus.", example_en: "That is their house." },
  { no: "tid", en: "time", pos: "noun", example: "Jeg har ikke tid.", example_en: "I don't have time." },
  { no: "hvis", en: "if", pos: "conj", example: "Hvis det regner, blir jeg hjemme.", example_en: "If it rains, I stay home." },
  { no: "vil", en: "will / want", pos: "verb", example: "Jeg vil lære.", example_en: "I want to learn." },
  { no: "hvordan", en: "how", pos: "adv", example: "Hvordan går det?", example_en: "How is it going?" },
  { no: "sa", en: "said", pos: "verb", example: "Han sa det.", example_en: "He said it." },
  { no: "hver", en: "each", pos: "det", example: "Hver dag trener jeg.", example_en: "Each day I train." },
  { no: "fortelle", en: "to tell", pos: "verb", example: "Fortell meg sannheten.", example_en: "Tell me the truth." },
  { no: "gjør", en: "does / do", pos: "verb", example: "Hva gjør du?", example_en: "What do you do?" },
  { no: "sett", en: "seen / set", pos: "verb", example: "Jeg har sett filmen.", example_en: "I have seen the movie." },
  { no: "tre", en: "three", pos: "num", example: "Jeg har tre venner.", example_en: "I have three friends." },
  { no: "ønsker", en: "wants", pos: "verb", example: "Hun ønsker hjelp.", example_en: "She wants help." },
  { no: "luft", en: "air", pos: "noun", example: "Frisk luft er godt.", example_en: "Fresh air is good." },
  { no: "godt", en: "good / well", pos: "adv", example: "Det smaker godt.", example_en: "It tastes good." },
  { no: "også", en: "also", pos: "adv", example: "Jeg kommer også.", example_en: "I am coming too." },
  { no: "spille", en: "to play", pos: "verb", example: "Jeg liker å spille.", example_en: "I like to play." },
  { no: "liten", en: "small", pos: "adj", example: "En liten katt.", example_en: "A small cat." },
  { no: "ende", en: "end", pos: "noun", example: "Slutten er nær.", example_en: "The end is near." },
  { no: "sette", en: "to set / put", pos: "verb", example: "Sett det der.", example_en: "Put it there." },
  { no: "hjem", en: "home", pos: "noun", example: "Jeg går hjem.", example_en: "I go home." },
  { no: "lese", en: "to read", pos: "verb", example: "Jeg leser en bok.", example_en: "I read a book." },
  { no: "hånd", en: "hand", pos: "noun", example: "Hold hånden min.", example_en: "Hold my hand." },
  { no: "stor", en: "big", pos: "adj", example: "Et stort hus.", example_en: "A big house." },
  { no: "selv", en: "self", pos: "pron", example: "Jeg gjør det selv.", example_en: "I do it myself." },
  { no: "her", en: "here", pos: "adv", example: "Kom her.", example_en: "Come here." },
  { no: "må", en: "must", pos: "verb", example: "Jeg må gå.", example_en: "I must go." },
  { no: "høy", en: "high", pos: "adj", example: "Et høyt fjell.", example_en: "A high mountain." },
  { no: "slik", en: "such / like this", pos: "det", example: "Gjør det slik.", example_en: "Do it like this." },
  { no: "hvorfor", en: "why", pos: "adv", example: "Hvorfor er du her?", example_en: "Why are you here?" },
  { no: "spør", en: "ask", pos: "verb", example: "Spør læreren.", example_en: "Ask the teacher." },
  { no: "menn", en: "men", pos: "noun", example: "To menn står der.", example_en: "Two men stand there." },
  { no: "gikk", en: "went", pos: "verb", example: "Jeg gikk hjem.", example_en: "I went home." },
  { no: "lys", en: "light", pos: "noun", example: "Lyset er sterkt.", example_en: "The light is strong." },
  { no: "trenger", en: "need", pos: "verb", example: "Jeg trenger hjelp.", example_en: "I need help." },
  { no: "huset", en: "the house", pos: "noun", example: "Huset er stort.", example_en: "The house is big." },
  { no: "bilde", en: "picture", pos: "noun", example: "Et fint bilde.", example_en: "A nice picture." },
  { no: "prøve", en: "to try", pos: "verb", example: "Prøv igjen.", example_en: "Try again." },
  { no: "oss", en: "us", pos: "pron", example: "Bli med oss.", example_en: "Join us." },
  { no: "igjen", en: "again", pos: "adv", example: "Si det igjen.", example_en: "Say it again." },
  { no: "dyr", en: "animal", pos: "noun", example: "Et stort dyr.", example_en: "A big animal." },
  { no: "punkt", en: "point", pos: "noun", example: "Et viktig punkt.", example_en: "An important point." },
  { no: "mor", en: "mother", pos: "noun", example: "Min mor.", example_en: "My mother." },
  { no: "verden", en: "world", pos: "noun", example: "Verden er stor.", example_en: "The world is big." },
  { no: "nær", en: "near", pos: "adv", example: "Kom nær.", example_en: "Come closer." },
  { no: "far", en: "father", pos: "noun", example: "Min far.", example_en: "My father." },
  { no: "ny", en: "new", pos: "adj", example: "En ny bil.", example_en: "A new car." },
  { no: "arbeid", en: "work", pos: "noun", example: "Jeg liker arbeidet.", example_en: "I like the work." },
  { no: "ta", en: "to take", pos: "verb", example: "Ta boken.", example_en: "Take the book." },
  { no: "få", en: "to get", pos: "verb", example: "Jeg får hjelp.", example_en: "I get help." },
  { no: "sted", en: "place", pos: "noun", example: "Et fint sted.", example_en: "A nice place." },
  { no: "leve", en: "to live", pos: "verb", example: "Jeg vil leve her.", example_en: "I want to live here." },
  { no: "tilbake", en: "back", pos: "adv", example: "Kom tilbake.", example_en: "Come back." },
  { no: "bare", en: "only / just", pos: "adv", example: "Jeg er bare trøtt.", example_en: "I am just tired." },
  { no: "mann", en: "man", pos: "noun", example: "En mann går.", example_en: "A man walks." },
  { no: "år", en: "year", pos: "noun", example: "Ett år går fort.", example_en: "A year goes fast." },
  { no: "kom", en: "came", pos: "verb", example: "Han kom hjem.", example_en: "He came home." },
  { no: "alle", en: "all", pos: "pron", example: "Alle er her.", example_en: "Everyone is here." },
  { no: "god", en: "good", pos: "adj", example: "En god dag.", example_en: "A good day." },
  { no: "meg", en: "me", pos: "pron", example: "Gi meg den.", example_en: "Give it to me." },
  { no: "gi", en: "to give", pos: "verb", example: "Gi meg boken.", example_en: "Give me the book." }
];